/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : PomodoroViewController.sm
 */


#import "statemap.h"

// Forward declarations.
@class PomodoroFSM;
@class PomodoroFSM_Suspended;
@class PomodoroFSM_Running;
@class PomodoroFSM_Done;
@class PomodoroFSM_Break;
@class PomodoroFSM_Default;
@class PomodoroViewControllerState;
@class PomodoroViewControllerContext;
@class PomodoroViewController;

@interface PomodoroViewControllerState : SMCState
{
}
- (void)Entry:(PomodoroViewControllerContext*)context;
- (void)Exit:(PomodoroViewControllerContext*)context;

- (void)pressPomodoro:(PomodoroViewControllerContext*)context;
- (void)timeOut:(PomodoroViewControllerContext*)context;

- (void)Default:(PomodoroViewControllerContext*)context;
@end

@interface PomodoroFSM : NSObject
{
}
+ (PomodoroFSM_Suspended*)Suspended;
+ (PomodoroFSM_Running*)Running;
+ (PomodoroFSM_Done*)Done;
+ (PomodoroFSM_Break*)Break;
@end

@interface PomodoroFSM_Default : PomodoroViewControllerState
{
}
@end

@interface PomodoroFSM_Suspended : PomodoroFSM_Default
{
}
 -(void)Entry:(PomodoroViewControllerContext*)context;
- (void)pressPomodoro:(PomodoroViewControllerContext*)context;
@end

@interface PomodoroFSM_Running : PomodoroFSM_Default
{
}
 -(void)Entry:(PomodoroViewControllerContext*)context;
 -(void)Entry:(PomodoroViewControllerContext*)context;
- (void)pressPomodoro:(PomodoroViewControllerContext*)context;
- (void)timeOut:(PomodoroViewControllerContext*)context;
@end

@interface PomodoroFSM_Done : PomodoroFSM_Default
{
}
 -(void)Entry:(PomodoroViewControllerContext*)context;
- (void)pressPomodoro:(PomodoroViewControllerContext*)context;
@end

@interface PomodoroFSM_Break : PomodoroFSM_Default
{
}
 -(void)Entry:(PomodoroViewControllerContext*)context;
 -(void)Entry:(PomodoroViewControllerContext*)context;
- (void)pressPomodoro:(PomodoroViewControllerContext*)context;
- (void)timeOut:(PomodoroViewControllerContext*)context;
@end

@interface PomodoroViewControllerContext : SMCFSMContext
{
    PomodoroViewController *_owner;
}
- (id)initWithOwner:(PomodoroViewController*)owner;
- (id)initWithOwner:(PomodoroViewController*)owner state:(SMCState*)aState;
- (PomodoroViewController*)owner;
- (PomodoroViewControllerState*)state;

- (void)enterStartState;

- (void)pressPomodoro;
- (void)timeOut;
@end


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
