/*
* generated by Xtext
*/
package org.xtext.example.contentassist;

import org.xtext.example.contentassist.AbstractEntityProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EntityProposalProvider extends AbstractEntityProposalProvider {

}
